modLoader="javafml"
loaderVersion="[36,)"
license="license.txt"
issueTrackerURL="https://github.com/InfinityRaider/InfinityLib/issues/"

[[mods]]
modId="infinitylib"
version="1.16.5-2.0.3"
displayName="InfinityLib"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/infinitylib/files"
displayURL="https://www.curseforge.com/minecraft/mc-mods/infinitylib"
logoFile="logo.png"
authors="InfinityRaider"
description='''
Library Mod.
'''

[[dependencies.infinitylib]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="AFTER"
    side="BOTH"
