modLoader="javafml"
loaderVersion="[40,)"
license="license.txt"
issueTrackerURL="https://github.com/InfinityRaider/InfinityLib/issues/"

[[mods]]
modId="infinitylib"
version="1.18.2-2.1.0"
displayName="InfinityLib"
displayURL="https://www.curseforge.com/minecraft/mc-mods/infinitylib"
logoFile="logo.png"
authors="InfinityRaider"
description='''
Library Mod.
'''

[[dependencies.infinitylib]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="AFTER"
    side="BOTH"
